project_id = "pyocqorzbsshawgknmpr"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.cleanup-expired-vibes]
    verify_jwt = false
  [functions.create-checkout-session]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.notify-new-signup]
    verify_jwt = false
  [functions.notify-new-vibe]
    verify_jwt = false
  [functions.stripe-credits-webhook]
    verify_jwt = false
  [functions.accept-partner-invite]
    verify_jwt = false
  [functions.scrape-instagram-feed]
    verify_jwt = false
