project_id = "pyocqorzbsshawgknmpr"

[functions.stripe-credits-webhook]
verify_jwt = false

[functions.notify-new-signup]
verify_jwt = false

[functions.notify-new-vibe]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
